userspace: Add support for conntrack ALGs.
XXX: Probe for supported ALGs first.

Signed-off-by: Joe Stringer <joestringer@nicira.com>
---
GCC-4.9.2-10 (Debian) prints this error, but successfully compiles:

../lib/ofp-actions.c:4461:17: error: undefined identifier 'IPPORT_FTP'

This is provided by netinet/in.h, which is included, so I'm at a loss as
to how to avoid this (other than defining our own IPPORT_FTP..).